services:
  - type: web
    name: crawlx-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: HOST
        value: 0.0.0.0
      - key: UVICORN_RELOAD
        value: "false"
      - key: CORS_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
